from typing import Protocol


class RebalanceConfigPort(Protocol):
    def get_asset_id_by_ticker(self, ticker: str) -> str | None: ...
    def select_all_active_with_ticker(self) -> list[dict]: ...
    def upsert(self, records: list[dict], unique_key: list[str]) -> None: ...


class RebalancePlanPort(Protocol):
    def insert_plan(self, record: dict) -> None: ...
    def mark_email_sent(self, plan_id: str) -> None: ...
    def load_current_weights(self) -> dict[str, float]: ...
    def get_latest(self) -> dict | None: ...
