from typing import Protocol


class TableRepositoryPort(Protocol):
    def select(self, params: dict) -> dict | None: ...
    def select_all(self) -> list: ...
    def select_all_by(self, params: dict) -> list: ...
    def insert(self, records: list[dict]) -> None: ...
    def upsert(self, records: list[dict], unique_key: list[str]) -> None: ...
    def update(self, params: dict, data: dict) -> None: ...
    def delete(self, params: dict) -> None: ...


class RepositoryFactoryPort(Protocol):
    def get(self, table_name: str) -> TableRepositoryPort: ...


class AssetAnalyticsPort(Protocol):
    def get_most_recent_asset_data(self): ...
    def get_portfolio_price_history(self, tickers: list): ...
    def get_asset_tags(self): ...
    def get_asset_history(self): ...
    def get_asset_snapshot(self, ticker: str, start_date: str, end_date: str): ...


class PortfolioQueryPort(Protocol):
    def get_unrealized_profit(self, from_date: str | None = None, to_date: str | None = None): ...
