"""create_database_object

Revision ID: 1ecedcc752f8
Revises: 
Create Date: 2026-01-10 21:48:08.620364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ecedcc752f8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "asset",
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('external_id', sa.String, unique=True),
        sa.Column('name', sa.String),
        sa.Column('description', sa.String),
        sa.Column('source_name', sa.String),
        sa.Column('is_active', sa.Boolean, default=True),
        sa.Column('created_datetime', sa.DateTime, default=sa.func.now()),
        sa.Column('updated_datetime', sa.DateTime),
        # schema='app'
    )

    op.create_table(
        "tag",
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('name', sa.String, unique=True),
        sa.Column('description', sa.String),
        sa.Column('tag_type_id', sa.Integer, sa.ForeignKey('tag_type.id')),
        sa.Column('is_active', sa.Boolean, default=True),
        sa.Column('created_datetime', sa.DateTime, default=sa.func.now()),
        sa.Column('updated_datetime', sa.DateTime),
        # schema='app'
    )

    op.create_table(
        "tag_type",
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('name', sa.String, unique=True),
        sa.Column('is_active', sa.Boolean, default=True),
        sa.Column('created_datetime', sa.DateTime, default=sa.func.now()),
        sa.Column('updated_datetime', sa.DateTime),
        # schema='app'
    )

    op.create_table(
        "asset_tag",
        sa.Column('asset_id', sa.Integer, sa.ForeignKey('asset.id'), primary_key=True),
        sa.Column('tag_id', sa.Integer, sa.ForeignKey('tag.id'), primary_key=True),
        sa.Column('is_active', sa.Boolean, default=True),
        sa.Column('created_datetime', sa.DateTime, default=sa.func.now()),
        sa.Column('updated_datetime', sa.DateTime),
        # schema='app'
    )


    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('asset_tag')
    op.drop_table('tag_type')
    op.drop_table('tag')
    op.drop_table('asset')

    # ### end Alembic commands ###
